MvcShoping/Models/Cart.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MvcShoping.Models
{
    public class Cart
    {
        [DisplayName("选购商品")]
        [Required]
        public Product product { get; set; }

        [DisplayName("选购数量")]
        [Required]
        public int Amount { get; set; }


    }
}

MvcShoping/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcShoping.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        [HttpPost]
        public ActionResult AddToCart(int productId, int amount)
        {
            return View();
        }
        /// <summary>
        /// 显示当前购物车项目
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 移除购物车项目
        /// </summary>
        /// <param name="productId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Remove(int productId)
        {
            return View();
        }
        /// <summary>
        /// 更新购物车中特定项目的购买数量
        /// </summary>
        /// <param name="productId"></param>
        /// <param name="NewAmount"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateAmount(int productId, int NewAmount)
        {
            return View();
        }
    }
}

MvcShoping/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcShoping.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        // GET: Order
        /// <summary>
        /// 显示完成的订单窗体页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Complate()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Complate(FormCollection form)
        {
            //TODO:将订单信息与购物协和信息写入数据库

            //TODO:订单完成后必须清空现在的购物车信息

            //TODO:生而为人 不可自大骄傲 也不必妄自菲薄，

            //订单完成后返回网站首页
            return RedirectToAction("Index", "Home");
        }

    }
}

MvcShoping/Views/Cart/Index.cshtml
@model  List<MvcShoping.Models.Cart>

@{
    /**/
    ViewBag.Title = "Index";
    var ajaxOption = new AjaxOptions()
    {
        OnSuccess = "RemoveCartSuccess",
        OnFailure = "RemoveCartFailure",
        Confirm = "您确定要从购物车移除这个商品吗？",
        HttpMethod = "Post"
    };
}
@section scripts{
    @Scripts.Render("~/boundles/jqueryval")
    <script>
        function RemoveCartSuccess() {
            alert('移除购物车成功');
            location.reload();
        }
        function RemoveCartFailure(xhr) {
            alert('移除购物车失败（HTTP状态代码：' + xhr.status + '）');
        }
    </script>
}
<h2>购物车列表</h2>
@using (Html.BeginForm("UpdateAmount", "Cart"))
{
    <table>
        <tr>
            <th>产品名称</th>
            <th>单价</th>
            <th>数量</th>
            <th>小计</th>
            <th></th>
        </tr>
        @{ int subTotal = 0;}
        @for (int i = 0; i < Model.Count; i++)
        {
            subTotal += Model[i].product.Price * Model[i].Amount;
            var ddlAmountList = new SelectList(Enumerable.Range(1, 10), Model[i].Amount);
            @Html.HiddenFor(modelItem => Model[i].product.Id)
            <tr>
                <td>@Html.DisplayFor(modelItem => Model[i].product.Name)</td>
                <td>NT$ @(Model[i].product.Price)</td>
                <td>@Html.DropDownListFor(modelItem => Model[i].Amount, ddlAmountList)</td>
                <td>NT$ @(Model[i].product.Price * Model[i].Amount)</td>
                <td>@Ajax.ActionLink("删除", "Remove", new { productId = Model[i].product.Id }, ajaxOption)</td>
            </tr>
        }
        <tr>
            <th></th>
            <th></th>
            <th>总价</th>
            <th id="subtotal"> NT$ @subTotal</th>
            <th></th>
        </tr>
    </table>
    <p>
        <input type="submit" value="更新数量" />
        <input type="button" value="完成订单" onclick="location.href='@Url.Action("Complate","Order")';" />
    </p>
}