MvcShoping/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcShoping.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        [HttpPost]
        public ActionResult AddToCart(int productId, int amount)
        {
            return View();
        }
        /// <summary>
        /// 显示当前购物车项目
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 移除购物车项目
        /// </summary>
        /// <param name="productId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Remove(int productId)
        {
            return View();
        }
        /// <summary>
        /// 更新购物车中特定项目的购买数量
        /// </summary>
        /// <param name="productId"></param>
        /// <param name="NewAmount"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateAmount(int productId, int NewAmount)
        {
            return View();
        }
    }
}

MvcShoping/Controllers/MemberController.cs
using MvcShoping.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcShoping.Controllers
{
    public class MemberController : Controller
    {
        /// <summary>
        /// 会员注册页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Register()
        {
            return View();
        }
        /// <summary>
        /// 写入会员信息
        /// </summary>
        /// <param name="member"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Register([Bind(Exclude ="RegisterOn,AuthCode")]Member member)
        {
            return View();
        }
        /// <summary>
        /// 显示会员登陆页面
        /// </summary>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        /// <summary>
        /// 运行会员登录
        /// </summary>
        /// <param name="email"></param>
        /// <param name="password"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Login(string email, string password, string returnUrl)
        {
            if (validateUser(email, password))
            {
                FormsAuthentication.SetAuthCookie(email, false);
                if (String.IsNullOrEmpty(returnUrl))
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return Redirect(returnUrl);
                }
            }
            ModelState.AddModelError("", "您输入的账号或密码错误！");
            return View();
        }

        private bool validateUser(string email, string password)
        {
            throw new NotImplementedException();
        }
        /// <summary>
        /// 注销登录
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            //清除窗口的cookies
            FormsAuthentication.SignOut();

            //清除所有曾经写过的session信息
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

MvcShoping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <header>
            <nav>
                @Html.ActionLink("首页","Index","Home")|@Html.ActionLink("购物车","Index","Cart")
                @if(User.Identity.IsAuthenticated)
                {
                    @:@Html.ActionLink("注销","Logout","Member")
                }
                else
                {
                    @:|@Html.ActionLink("登录","Login","Member")
                    @:|@Html.ActionLink("注册","Register","Member")
                }
            </nav>
        </header>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>